"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Surabhi Arun, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: sa59594
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    if key < 2 or key >= len(string):
        return string
    rails = [[] for _ in range(key)]
    row = 0
    direction = 1
    for ch in string:
        rails[row].append(ch)
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        row += direction
    result = ""
    for track in rails:
        result += "".join(track)
    return result


def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    n = len(string)
    marker = [[False] * n for _ in range(key)]
    row = 0
    direction = 1
    for col in range(n):
        marker[row][col] = True
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        row += direction

    grid = [[''] * n for _ in range(key)]
    idx = 0
    for r in range(key):
        for c in range(n):
            if marker[r][c]:
                grid[r][c] = string[idx]
                idx += 1

    decoded = ""
    row = 0
    direction = 1
    for col in range(n):
        decoded += grid[row][col]
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        row += direction

    return decoded


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    s = string.lower()
    out = ""
    for ch in s:
        if 'a' <= ch <= 'z':
            out += ch
    return out


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    shift = ord(p) - ord('a')
    val = ord(s) - ord('a')
    return chr((val + shift) % 26 + ord('a'))


def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    shift = ord(p) - ord('a')
    val = ord(s) - ord('a')
    return chr((val - shift) % 26 + ord('a'))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    text = filter_string(string)
    key = filter_string(phrase)
    if not key:
        return ""
    out = ""
    for i, ch in enumerate(text):
        out += encode_character(key[i % len(key)], ch)
    return out


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    text = filter_string(string)
    key = filter_string(phrase)
    if not text or not key:
        return ""
    out = ""
    for i, ch in enumerate(text):
        out += decode_character(key[i % len(key)], ch)
    return out


def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)
    plaintext = input()
    # read the key from stdin (terminal/input)
    k = int(input())
    # encrypt and print the encoded text using rail fence cipher
    encrypted = rail_fence_encode(plaintext, k)
    print(f"Plain Text: {plaintext}")
    print(f"Key: {k}")
    print(f"Encoded Text: {encrypted}\n")

    # read encoded text from stdin (terminal/input)
    cipher_in = input()
    # read the key from stdin (terminal/input)
    k2 = int(input())
    # decrypt and print the plain text using rail fence cipher
    decrypted = rail_fence_decode(cipher_in, k2)
    print(f"Encoded Text: {cipher_in}")
    print(f"Enter Key: {k2}")
    print(f"Decoded Text: {decrypted}\n")

    # read the plain text from stdin (terminal/input)
    pt2 = input()
    # read the pass phrase from stdin (terminal/input)
    passphrase = input()
    # encrypt and print the encoded text using Vigenere cipher
    enc2 = vigenere_encode(pt2, passphrase)
    print(f"Plain Text: {pt2}")
    print(f"Pass Phrase: {passphrase}")
    print(f"Encoded Text: {enc2}\n")

    # read the encoded text from stdin (terminal/input)
    cipher2 = input()
    # read the pass phrase from stdin (terminal/input)
    pass2 = input()
    # decrypt and print the plain text using Vigenere cipher
    dec2 = vigenere_decode(cipher2, pass2)
    print(f"Encoded Text: {cipher2}")
    print(f"Pass Phrase: {pass2}")
    print(f"Decoded Text: {dec2}\n")


# Do NOT modify the following code.
if __name__ == "__main__":
    main()