"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Surabhi Arun, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: sa59594
"""


# TODO: implement this function. You may delete this comment after you are done.
def railencode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    if key < 2 or key >= len(string):
        return string
    # build rails
    rails = ['' for _ in range(key)]
    idx = 0
    down = True
    for c in string:
        rails[idx] += c
        if down:
            idx += 1
            if idx == key:
                idx = key - 2
                down = False
        else:
            idx -= 1
            if idx < 0:
                idx = 1
                down = True
    out = ''
    for r in rails:
        out += r
    return out


# TODO: implement this function. You may delete this comment after you are done.
def raildecode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    if key < 2 or key >= len(string):
        return string
    n = len(string)
    # mark positions
    mark = [[False]*n for _ in range(key)]
    r = 0
    down = True
    for i in range(n):
        mark[r][i] = True
        if down:
            r += 1
            if r == key:
                r = key - 2
                down = False
        else:
            r -= 1
            if r < 0:
                r = 1
                down = True
    # fill characters
    grid = [['']*n for _ in range(key)]
    pos = 0
    for i in range(key):
        for j in range(n):
            if mark[i][j] and pos < n:
                grid[i][j] = string[pos]
                pos += 1
    # read zigzag
    res = ''
    r = 0
    down = True
    for i in range(n):
        res += grid[r][i]
        if down:
            r += 1
            if r == key:
                r = key - 2
                down = False
        else:
            r -= 1
            if r < 0:
                r = 1
                down = True
    return res


# TODO: implement this function. You may delete this comment after you are done.
def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    s = string.lower()
    out = ''
    for ch in s:
        if 'a' <= ch <= 'z':
            out += ch
    return out


# TODO: implement this function. You may delete this comment after you are done.
def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    po = ord(p) - ord('a')
    so = ord(s) - ord('a')
    val = po + so
    if val >= 26:
        val -= 26
    return chr(val + ord('a'))


# TODO: implement this function. You may delete this comment after you are done.
def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    po = ord(p) - ord('a')
    so = ord(s) - ord('a')
    val = so - po
    if val < 0:
        val += 26
    return chr(val + ord('a'))


# TODO: implement this function. You may delete this comment after you are done.
def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    f = filter_string(string)
    out = ''
    L = len(phrase)
    for i in range(len(f)):
        p = phrase[i % L]
        out += encode_character(p, f[i])
    return out


# TODO: implement this function. You may delete this comment after you are done.
def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    out = ''
    L = len(phrase)
    for i, ch in enumerate(string):
        p = phrase[i % L]
        out += decode_character(p, ch)
    return out


# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)
    pt = input().strip()
    
    # read the key from stdin (terminal/input)
    k = int(input().strip())
    
    # encrypt and print the encoded text using rail fence cipher
    enc = railencode(pt, k)
    print("Rail Fence Cipher")
    print()
    print("Plain Text:", pt)
    print("Key:", k)
    print("Encoded Text:", enc)
    print()
    
    # read encoded text from stdin (terminal/input)
    ct = input().strip()
    
    # read the key from stdin (terminal/input)
    dk = int(input().strip())
    
    # decrypt and print the plain text using rail fence cipher
    dec = raildecode(ct, dk)
    print("Encoded Text:", ct)
    print("Enter Key:", dk)
    print("Decoded Text:", dec)
    print()
    
    # read the plain text from stdin (terminal/input)
    pv = input().strip()
    
    # read the pass phrase from stdin (terminal/input)
    ph = input().strip()
    
    # encrypt and print the encoded text using Vigenere cipher
    ev = vigenere_encode(pv, ph)
    print("Vigenere Cipher")
    print()
    print("Plain Text:", pv)
    print("Pass Phrase:", ph)
    print("Encoded Text:", ev)
    print()
    # read the encoded text from stdin (terminal/input)
    cv = input().strip()
    # read the pass phrase from stdin (terminal/input)
    ph2 = input().strip()
    # decrypt and print the plain text using Vigenere cipher
    dv = vigenere_decode(cv, ph2)
    print("Encoded Text:", cv)
    print("Pass Phrase:", ph2)
    print("Decoded Text:", dv)
    

# Do NOT modify the following code.
if __name__ == "__main__":
    main()
